## CEBD 1260 Introduction to big data and machine learning

## Session 2: General methodologies in machine learning

in this notebook, we will practice general methods of machine learning 

NOTE: for each activity below, please refer and correspond with our course slides

Instructor: Yimin Nie

email: ymnie888@gmail.com

#### Submission of your assignments:

each assignment is given in this notebook, please complete them by creating another jupyter notebook and submit on dropbox

## import important libs

In [7]:
import numpy as np   # import numpy
import pandas as pd  # import pandas
import os
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

## Activity 1:  read your data, split input and target variables for your data

In [8]:
# DATA_PATH
# DATA_PATH = r'C:\Users\enxxmnx\OneDrive - Ericsson AB\workspace\training\data\city_bike_share'
# DATA_PATH = r'C:\\Users\\enxxmnx\\OneDrive - Ericsson AB\\workspace\\training\\data\\city_bike_share' # this is also working
DATA_PATH = r'C:\Users\user\Desktop'

In [16]:
df = pd.read_csv((DATA_PATH+r'\sessions.csv'))
# df = pd.read_csv(os.path.join(DATA_PATH,'train.csv'))

In [17]:
#get some info from data frame
print(df.shape)

(10567737, 6)


In [18]:
# check the data 
df.head()
# df.head(3)
# df.tail()

user_id          action action_type        action_detail  \
0  d1mm9tcy42          lookup         NaN                  NaN   
1  d1mm9tcy42  search_results       click  view_search_results   
2  d1mm9tcy42          lookup         NaN                  NaN   
3  d1mm9tcy42  search_results       click  view_search_results   
4  d1mm9tcy42          lookup         NaN                  NaN   

       device_type  secs_elapsed  
0  Windows Desktop         319.0  
1  Windows Desktop       67753.0  
2  Windows Desktop         301.0  
3  Windows Desktop       22141.0  
4  Windows Desktop         435.0

In [19]:
df.info() # this give you more infor about data type of each column

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10567737 entries, 0 to 10567736
Data columns (total 6 columns):
user_id          object
action           object
action_type      object
action_detail    object
device_type      object
secs_elapsed     float64
dtypes: float64(1), object(5)
memory usage: 483.8+ MB


In [20]:
des = df.describe() # describe the statistical property of the data
des

secs_elapsed
count  1.043171e+07
mean   1.940581e+04
std    8.888424e+04
min    0.000000e+00
25%    2.290000e+02
50%    1.147000e+03
75%    8.444000e+03
max    1.799977e+06

In [26]:
# get input and target from your data, X is the input, y is the target
y = df['secs_elapsed'].values# define target 
y

array([   319.,  67753.,    301., ..., 200125.,  17624.,   1221.])

In [29]:
# get a full list of features we will use for input
features = [f for f in df.columns.values if f not in ['secs_elapsed']] 
print(features)

['user_id', 'action', 'action_type', 'action_detail', 'device_type']


In [30]:
X = df[features] # get X

In [31]:
print(X.shape,len(y))

(10567737, 5) 10567737


In [32]:
X.head()

user_id          action action_type        action_detail  \
0  d1mm9tcy42          lookup         NaN                  NaN   
1  d1mm9tcy42  search_results       click  view_search_results   
2  d1mm9tcy42          lookup         NaN                  NaN   
3  d1mm9tcy42  search_results       click  view_search_results   
4  d1mm9tcy42          lookup         NaN                  NaN   

       device_type  
0  Windows Desktop  
1  Windows Desktop  
2  Windows Desktop  
3  Windows Desktop  
4  Windows Desktop

#### Assignment 1: 

please read and split input and output for your own project data and understanding in details

## Activity 2:  identify categorical and numerical features 

In [33]:
# print data type for each feature
for f in features:
    print(" {}: {}".format(f,df[f].dtype))

 user_id: object
 action: object
 action_type: object
 action_detail: object
 device_type: object


In [34]:
#pickup all features what are categorical
cat_features = []
for f in features:
    if str(df[f].dtype) == 'object':
        cat_features.append(f)
print(cat_features)

['user_id', 'action', 'action_type', 'action_detail', 'device_type']


DISCUSSIN: is it true above?? what are categorical features you think?

In [35]:
# sometimes we need to really see if one feature is categorical based on our domain knowledge or common sense
cat_features = []
for f in features:
    if str(df[f].dtype) in ['object','int64']:
        cat_features.append(f)
print(cat_features)

['user_id', 'action', 'action_type', 'action_detail', 'device_type']


#### Assignment 2: 

please identify categorical features for your own data, you need to use some coding and your own understanding from the data

## Activity 3:  split total data by train, test and validation

In [36]:
from sklearn.model_selection import train_test_split

In [37]:
# split 20% data as test data
train_X,test_X,train_y,test_y = train_test_split(X,y,shuffle=True,random_state=2019,test_size=0.2)
print(train_X.shape,test_X.shape,len(train_y),len(test_y))

(8454189, 5) (2113548, 5) 8454189 2113548


In [38]:
# split another 20% data as valid data, NOTE that you cannot touch test data again
train_X,valid_X,train_y,valid_y = train_test_split(train_X,train_y,shuffle=True,random_state=668,test_size=0.2)
print(train_X.shape,valid_X.shape,len(train_y),len(valid_y))

(6763351, 5) (1690838, 5) 6763351 1690838


#### Assignment 3: 

please split your own project data train,valid,test by 20%,25% from the total data set

## Activity 4: split overall data set using cross validation strategies

In [39]:
from sklearn.model_selection import KFold,StratifiedKFold

In [40]:
kf = KFold(n_splits=5)
for train_idx,valid_idx in kf.split(X,y):
    print(train_idx,valid_idx)

[ 2113548  2113549  2113550 ... 10567734 10567735 10567736] [      0       1       2 ... 2113545 2113546 2113547]
[       0        1        2 ... 10567734 10567735 10567736] [2113548 2113549 2113550 ... 4227093 4227094 4227095]
[       0        1        2 ... 10567734 10567735 10567736] [4227096 4227097 4227098 ... 6340640 6340641 6340642]
[       0        1        2 ... 10567734 10567735 10567736] [6340643 6340644 6340645 ... 8454187 8454188 8454189]
[      0       1       2 ... 8454187 8454188 8454189] [ 8454190  8454191  8454192 ... 10567734 10567735 10567736]


In [41]:
for train_idx,valid_idx in kf.split(X,y):
    train_X = X.loc[train_idx]
    train_y = y[train_idx]
    
    valid_X = X.loc[valid_idx]
    valid_y = y[valid_idx]

#### Assignment 4: 

practice cross validation split by your own data

## Activity 5: practice different loss functions provided by sklearn toolkit


In [22]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,log_loss

In [23]:
x = [0.4,0.7,1.5,2.9]
x_hat = [0.3,0.67,1.6,2.87]
mean_absolute_error(x,x_hat)

0.06499999999999996

In [24]:
x=[1,0,1,0,0,0,1,1,0,0,0]
x_hat =[0.98,0.12,0.86,0.04,0.004,0.01,0.998,0.976,0.005,0.025,0.017]
log_loss(x,x_hat)

0.0388645931105278

#### Assignment 5: 

refer the math defination of loss function in our slides and try to understand how to code them in sklearn